# Generated by Django 3.2.13 on 2024-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chef'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ('position',), 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(blank=True, upload_to='chefs/'),
        ),
    ]
